//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAMPANYALAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KAMPANYALAR()
        {
            this.URUNLER = new HashSet<URUNLER>();
        }
    
        public int KAMPANYAID { get; set; }
        public string KAMPANYAADI { get; set; }
        public Nullable<decimal> INDIRIMORANI { get; set; }
        public string KAMPANYAACIKLAMA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<URUNLER> URUNLER { get; set; }
    }
}
