//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations; //uyarilar icin

    public partial class MUSTERILER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MUSTERILER()
        {
            this.SATIS = new HashSet<SATIS>();
        }
    
        public int MUSTERIID { get; set; }

        [Required(ErrorMessage = "MUSTERI ADINI GIRINIZ!")]
        [StringLength(50,ErrorMessage ="EN FAZLA 50 KARAKTERLIK ISIM GIRINIZ!")]
        
        public string MUSTERIAD { get; set; }

        [Required(ErrorMessage = "MUSTERI SOYADINI GIRINIZ!")]
        public string MUSTERISOYAD { get; set; }
        public string MUSTERITELNO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATIS> SATIS { get; set; }
    }
}
