//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATISDETAY
    {
        public int SATISDETAYID { get; set; }
        public Nullable<int> SATISID { get; set; }
        public Nullable<int> URUNID { get; set; }
        public Nullable<int> ADET { get; set; }
        public Nullable<decimal> BIRIMFIYAT { get; set; }
    
        public virtual SATIS SATIS { get; set; }
        public virtual URUNLER URUNLER { get; set; }
    }
}
