//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcOtomasyon.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNLER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUNLER()
        {
            this.SATISDETAY = new HashSet<SATISDETAY>();
        }
    
        public int URUNID { get; set; }
        public Nullable<int> KATEGORIID { get; set; }
        public Nullable<int> KAMPANYAID { get; set; }
        public string URUNMARKA { get; set; }
        public string URUNMODEL { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<int> STOK { get; set; }
        public string URUNAD { get; set; }
    
        public virtual KAMPANYALAR KAMPANYALAR { get; set; }
        public virtual KATEGORILER KATEGORILER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATISDETAY> SATISDETAY { get; set; }
    }
}
